name: Deploy to Cloudflare Pages on tag

on:
  push:
    tags:
      - v*

env:
  BUN_VERSION: 1.1.2
  PROJECT_NAME: portfolio
  OUTPUT_DIRECTORY: dist

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #v4.1.4
      - name: Setup Bun
        uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 #v1.2.1
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Deploy
        id: deploy-preview
        uses: cloudflare/wrangler-action@a84dcc6dd36c8769fbff7e622308c8050fc41f4f #v3.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.OUTPUT_DIRECTORY }} --project-name=${{ env.PROJECT_NAME }} --branch=${{ github.ref }}
